---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.10.0
    app.quarkus.io/commit-id: a06c5574b6a8386827c4a13fb4568f29180834e2
    app.quarkus.io/vcs-uri: https://github.com/lucamolteni/akrivis.git
    app.quarkus.io/build-timestamp: 2025-01-17 - 14:06:02 +0000
  labels:
    app.kubernetes.io/name: akrivis-processor
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: akrivis-processor
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: akrivis-processor
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.10.0
    app.quarkus.io/commit-id: a06c5574b6a8386827c4a13fb4568f29180834e2
    app.quarkus.io/vcs-uri: https://github.com/lucamolteni/akrivis.git
    app.quarkus.io/build-timestamp: 2025-01-17 - 14:06:02 +0000
  labels:
    app.kubernetes.io/name: akrivis-processor
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: akrivis-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: akrivis-processor
      app.kubernetes.io/version: 1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/quarkus-version: 3.10.0
        app.quarkus.io/commit-id: a06c5574b6a8386827c4a13fb4568f29180834e2
        app.quarkus.io/vcs-uri: https://github.com/lucamolteni/akrivis.git
        app.quarkus.io/build-timestamp: 2025-01-17 - 14:06:02 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/name: akrivis-processor
        app.kubernetes.io/version: 1.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: scorecards-secret
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: DB_CONNECTION_STRING
                  name: scorecards-secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: scorecards-secret
          envFrom:
            - configMapRef:
                name: scorecards-configmap
          image: quay.io/lmolteni/akrivis-processor:latest
          imagePullPolicy: Always
          name: akrivis-processor
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
